###
# @name getEvents
GET http://localhost:3000/events
###

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Auuu",
  "description": "tcc half presentation",
  "date": "2024-06-17T00:00:00.00",
  "price": 99.99
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/

###
GET http://localhost:3000/events/{{ eventId }}


###
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
  "name": "Apresentação de TCC",
  "description": "Apresentação de TCC do meio do ano",
  "date": "2024-06-17T00:00:00.00",
  "price": 101
}

###
DELETE http://localhost:3000/events/{{ eventId }}

### @name getSpots
GET http://localhost:3000/events/{{ eventId }}/spots


### @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type: application/json

{
  "name": "A7"
}

### @deleteSpot
DELETE http://localhost:3000/events/{{ eventId }}/spots